### PR TITLE
Update mmap-alloc for the new nightly `Alloc` trait

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by fitzgen** [comment]
Note: I did not attempt to update any of the other crates in this repo that wee_alloc does not depend on.

**Comment by joshlf** [comment]
@fitzgen Is this the same code that's currently working for y'all in wee_alloc? Just want to make sure it's battle-tested since the CI tests are failing (and since I'm going to merge this first before fixing the other crates).

**Comment by fitzgen** [comment]
Yep!

See
https://github.com/rustwasm/wee_alloc/blob/master/wee_alloc/Cargo.toml#L37

**Comment by joshlf** [comment]
Superseded by #184.

**Pull request closed without merging**
