### PR TITLE
bsalloc: improve cache

### PR DESCRIPTION
**Pull request by teg**
I noticed some minor things as I'm looking through the code.

### CODE REVIEW

**Comment by joshlf** [comment]
Hi @teg, thanks for the PR!

@ezrosent and I are pretty busy right now, so we probably won't be able to get to this for a bit, but we really appreciate the PR! In the meantime, if you're interested in contributing beyond this PR, feel free to check out the issues and let me know if you have any questions about anything.

**Comment by teg** [comment]
Thanks @joshlf! Do you have a preferred communication channel for general questions? For now I thought I'd just file some PRs for stuff I notice as I try to wrap my head around the code, but take your time reviewing it.

**Comment by joshlf** [comment]
Comments on issues/PRs are fine, and email works fine too (hello@joshlf.com) for longer-form or more open discussion.

**Comment by joshlf** [comment]
Hey, sorry for the delay. The code looks good! If you wouldn't mind squashing the last two commits (the ones about the rng) into one, we'll merge!

**Comment by teg** [comment]
I won't be working on this.

**Pull request closed without merging**
