### PR TITLE
info: Fix typo in elfmalloc-performance.md

### PR DESCRIPTION
**Pull request by adrian5**

### CODE REVIEW

**Comment by joshlf** [comment]
Hey, can you edit the commit message to be something like `info: Fix typo in elfmalloc-performance.md`? Since we have a bunch of sub-projects, we try to preface all commit messages with the project name. Otherwise, I'm happy to merge.

**Comment by adrian5** [comment]
Updated. Let me know if this doesn't suffice/work.

**Comment by joshlf** [comment]
Sorry, I meant the commit message, not the title of this PR (although that's helpful too). I'd do it myself, but since the branch is in your repo, I can't make changes to it.

**Comment by adrian5** [comment]
I'm sorry, I've only ever done pull request to other repositories using the website's UI. I cloned my copy of your repo, checked out the `patch-1` branch and used `git commit --amend`. Somehow this required a merge too. I this correct, or should it remain a single commit?

If the latter, could you bear with me while I try to do my first proper commit from the command line? I'm still trying to figure out how.

**Comment by adrian5** [comment]
I'll start over, this is just wasting your time. I'll learn this through my own experiments. Sorry!

**Comment by joshlf** [comment]
No worries! I'm happy to help. Honestly, git can be pretty confusing even for people who have been using it for a long time.

**Pull request closed without merging**
