### PR TITLE
mmap-alloc: debug_assert! that sizes are non-zero

### LINKED ISSUE #81: mmap-alloc: debug_assert! that sizes are non-zero
It is undefined behavior (UB) to pass a zero-sized `Layout` to the `Alloc` trait's allocation methods. mmap-alloc's `MapAlloc` relies on size being non-zero for correctness. While this is allowed, we should still `debug_assert!` that requested sizes are zero in order to make debugging easier for our users.

### PR DESCRIPTION
**Pull request by Joezc**
Closes #81 

My first PR, let me know if something wrong.

### CODE REVIEW

**Comment by joshlf** [comment]
Welcome @Joezc , and thanks for the PR!

I think it'd actually be better to have these assertions at the beginning of each of the public methods to make it easier to tell what's going wrong (we sometimes call `map` after doing some math internally). In particular, `commit` and `uncommit`, and the `Alloc` methods `alloc`, `dealloc`, `usable_size`, `alloc_zeroed`, `realloc`, `grow_in_place`, and `shrink_in_place`. For the latter three, you should assert that both `layout.size()` and `new_layout.size()` are non-zero.

Looks good though, thanks!

**Comment by joshlf** [comment]
Looks like I messed up your PR by squashing some changes on master - that's my fault! You could try to rebase everything, although it might be easier for you to just open a new PR.

While you're at it, I know this is a nitpick, but could you change "bigger than 0" to "non-zero"? Best to be consistent with the wording that the docs use.

**Comment by Joezc** [comment]
Thanks for your mentoring! That is a big inspiration.  Now I just changed my code and opened another PR.

**Comment by joshlf** [comment]
You're very welcome! The more contributors the merrier :)

**Comment by joshlf** [comment]
Closed in favor of #86.

**Pull request closed without merging**
