### PR TITLE
test-scripts/check-copyright-comments.sh: Fix comment typo #70

### PR DESCRIPTION
**Pull request by abhijeetbhagat**

### CODE REVIEW

**Comment by joshlf** [comment]
Hi @abhijeetbhagat , welcome and thanks for the PR!

Can you modify the commit message to read as follows? Otherwise, looks good!

```text
test-scripts: Fix comment typo in check-copyright-comments.sh

Closes #70
```

**Comment by joshlf** [comment]
Sorry, I was referring to the commit message itself, not the title of this PR.

You can do that by checking out the branch you're working on, doing `git commit --amend` to amend the commit message, and then `git push --force` to push the changes (you have to use the `--force` flag because you're not adding a new commit, you're actually modifying an existing commit, and thus overwriting an existing commit when you push).

**Comment by joshlf** [comment]
If it'd be easier for you, I can also just take your work and put it in a separate PR with the corrected commit message (I can't correct this PR because I don't have write access to your fork of the repository).

**Comment by abhijeetbhagat** [comment]
Sorry for the late reply. This PR can be ignored as i've opened a new one with the proper commit message.

**Pull request closed without merging**
